ccnmtl/nepi

- media/js/dashboard.js
- nepi/main/models.py
- nepi/main/views.py
- nepi/templates/dashboard/reports.html
- requirements.txt
Stream the reports …
* Use StreamingHTTPResponse instead of constructing a ZIP file. Substantially speeds up the download.
* https://docs.djangoproject.com/en/1.7/howto/outputting-csv/#streaming-csv-files
> Optimize reporting

- nepi/main/views.py
Aggregate reports do not show average session scores. Create a custom "aggregate report" function rather than using the common progress report.
> Optimize Aggregate Reports

- nepi/main/models.py
- nepi/main/templatetags/progressreport.py
- nepi/main/tests/test_models.py
- nepi/main/tests/test_reports.py
- nepi/main/tests/test_views.py
- nepi/main/views.py
- nepi/templates/dashboard/group_details.html
- nepi/templates/dashboard/roster_details.html
- nepi/templates/dashboard/student_details.html
- nepi/urls.py
Time Spent & Time Elapsed calculations
Offer Group aggregate progress report as a download
HierarchyCache - stashing descendants during a report run
Refactoring + Testing
> Calculate duration

- nepi/main/models.py
- nepi/main/tests/test_models.py
- nepi/main/tests/test_reports.py
- nepi/main/tests/test_views.py
- nepi/main/views.py
> Completion Date - for downloadable report view

- nepi/main/admin.py
- nepi/templates/base.html
* register userpagevisit for admin
> Impersonate: switch to search interface

- nepi/main/tests/test_views.py
- nepi/main/views.py
Adding a feature flag here to allow superusers & editors to access and test language-specific content.
> Waffle Set Language

- nepi/activities/urls.py
- nepi/activities/views.py
- nepi/main/tests/test_views.py
- nepi/main/views.py
- nepi/urls.py
removing extraneous code + a little renaming
> Minor Code Cleanup

- nepi/templates/quizblock/question.html
- nepi/templates/quizblock/quizblock.html
And removing "rhetorical" block references.
> Quizblock - a few translations

- nepi/activities/admin.py
- nepi/activities/models.py
- nepi/activities/tests/test_models.py
- nepi/activities/tests/test_views.py
- nepi/activities/views.py
* handling the situation where users might have a double response created.
* increasing test coverage here.
> Retention Response multiple responses PMT# 101432

- nepi/templates/dashboard/reports.html
- nepi/templates/dashboard/tab_groups.html
Already resolved in production.
https://sentry.ccnmtl.columbia.edu/sentry-internal/nepi/group/736/
> Fixing hierarchy references. 

- nepi/templates/pagetree/edit_page.html
hide the tab content as well as the tabs themselves.
> tweak locking behavior

- nepi/templates/activities/dosageactivity.html
- nepi/templates/activities/dosageactivity_js.html
> Dosage activity - refine validation

- nepi/activities/views.py
remove local definition and use the one from the mixin
> Fix render_to_json_response reference

- media/css/main.css
- nepi/main/tests/test_views.py
- nepi/main/views.py
- nepi/templates/dashboard/group_details.html
- nepi/templates/dashboard/roster_details.html
- nepi/urls.py
> School Groups: Admin functionality to add many users

- nepi/main/tests/test_views.py
- nepi/main/views.py
- nepi/templates/dashboard/roster_details.html
- nepi/urls.py
> Bulk Add User: additional messaging

- nepi/activities/migrations/0003_auto_20150918_1435.py
- nepi/activities/models.py
- nepi/main/migrations/0004_auto_20150918_1435.py
> Conversation: remove character restrictions

- nepi/main/tests/test_reports.py
- nepi/main/views.py
* Use [completed metric](https://github.com/ccnmtl/nepi/pull/229) to count users who have really completed. (100% visits, plus valid pre/post test scores)
* tests
> Aggregate Report: Use better metric to determine "completed"

- nepi/templates/registration/login.html
* some browsers aren't displaying the form as expected
> tweak login form layout

- .bandit
- django.mk
- nepi/main/tests/factories.py
- package-lock.json
- requirements.txt
* ignoring false positives in test random number generation
> bandit: python security linting

- nepi/settings_shared.py
- nepi/templates/dashboard/people.html
- nepi/templates/dashboard/roster_details.html
- nepi/templates/dashboard/tab_groups.html
- nepi/templates/main/page.html
- nepi/templates/pagetree/clone_hierarchy.html
- nepi/templates/pagetree/edit_page.html
- nepi/templates/quizblock/edit_answer.html
- nepi/templates/quizblock/edit_question.html
- nepi/templates/registration/login.html
and all the tokens to the forms
> Add CSRF middleware

- nepi/templates/activities/calendarchart_js.html
- nepi/templates/activities/conversation_js.html
- nepi/templates/activities/retentionrate_js.html
> Add csrf token to ajax queries

- media/css/main.css
- requirements.txt
The upgraded version of compressor appears more sensitive to .css syntax errors. This PR corrects long standing mistakes in the .css.
> Upgrade django-compressor to 3.1 with .css fixes

- requirements.txt
> Revert "Bump urllib3 from 1.26.15 to 2.0.0"

- requirements.txt
> Revert "Bump faker from 23.2.1 to 23.3.0"

- requirements.txt
> Revert "Revert "Bump faker from 23.2.1 to 23.3.0""

- .github/workflows/build-and-test.yml
> Revert "Update build-and-test.yml"

- .github/workflows/build-and-test.yml
- django.mk
- js.mk
> Github Actions: separate make flake8 from make test

- nepi/settings_shared.py
> Update mail domain to our SES identity
